# Generated by Django 3.0.7 on 2020-07-24 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_disease', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='donorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('khulna', 'khulna'), ('dhaka', 'dhaka'), ('chittagong', 'chittagong')], max_length=40, null=True)),
                ('Conceived_before', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=25)),
                ('donor_status', models.BooleanField(default=False)),
                ('donation_status', models.BooleanField(default=False)),
                ('last_donation_date', models.DateTimeField(blank=True, null=True)),
                ('times_donated', models.IntegerField(default=0, null=True)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('Others', 'Others')], max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(max_length=14, null=True)),
                ('address', models.TextField()),
                ('comment_of_donor', models.TextField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_positive', models.DateTimeField(null=True)),
                ('first_negative', models.DateTimeField(null=True)),
                ('recovery_date', models.DateTimeField(null=True)),
                ('convinced_before', models.BooleanField(blank=True, null=True)),
                ('motivation_level', models.CharField(choices=[('Highly Interested', 'Highly Interested'), ('Interested', 'Interested'), ('Less Interested', 'Less Interested')], max_length=25, null=True)),
                ('regional_field', models.CharField(choices=[('khulna', 'khulna'), ('rajshahi', 'rajshahi'), ('dhaka', 'dhaka'), ('chittagong', 'chittagong')], max_length=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('volunteer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('disease', models.ManyToManyField(to='admin_2.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(blank=True, max_length=200, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='patient name')),
                ('emergency_contact', models.CharField(max_length=14, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=25)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('regional_field', models.CharField(choices=[('khulna', 'khulna'), ('rajshahi', 'rajshahi'), ('dhaka', 'dhaka'), ('chittagong', 'chittagong')], max_length=50, verbose_name='Area')),
                ('admission_registration_no', models.CharField(max_length=100)),
                ('plasma_req_form_img', models.ImageField(null=True, upload_to='')),
                ('emergency_contact_persons_name', models.CharField(max_length=100, null=True)),
                ('comment_of_patient', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('vol_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Volunteer Name')),
                ('unit_name', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('khulna', 'khulna'), ('dhaka', 'dhaka'), ('chittagong', 'chittagong')], max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='triagePatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='patient_name')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('Others', 'Others')], max_length=10)),
                ('age', models.IntegerField()),
                ('contact_number', models.CharField(max_length=14, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_positive', models.DateTimeField()),
                ('hospital_admit_dt', models.DateTimeField(blank=True, null=True)),
                ('hospital_release_dt', models.DateTimeField(blank=True, null=True)),
                ('area', models.CharField(choices=[('khulna', 'khulna'), ('dhaka', 'dhaka'), ('chittagong', 'chittagong')], max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotivatedDonorTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_don', models.IntegerField(blank=True, null=True, verbose_name='Number of Donation')),
                ('last_don_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Donation Date')),
                ('f_pos_ava', models.IntegerField(blank=True, null=True, verbose_name='Availability from first positive test')),
                ('f_neg_ava', models.IntegerField(blank=True, null=True, verbose_name='Availability from first negative test')),
                ('s_res_ava', models.IntegerField(blank=True, null=True, verbose_name='Availability from symptom resolution date')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_2.donorInfo')),
            ],
        ),
        migrations.CreateModel(
            name='DonorRequesterRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_2.donorInfo')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_2.Requester')),
            ],
        ),
    ]
