# Generated by Django 3.0.7 on 2020-07-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_2', '0002_auto_20200724_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinfo',
            name='disease',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='plasma_req_form_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='requester',
            name='unit_name',
            field=models.CharField(choices=[('khulna', 'khulna'), ('rajshahi', 'rajshahi'), ('dhaka', 'dhaka'), ('chittagong', 'chittagong')], max_length=100),
        ),
    ]
