# Generated by Django 3.0.7 on 2020-07-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_2', '0005_auto_20200726_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivateddonortable',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
